#cloud-config
manage_etc_hosts: true
timezone: $VM_TIMEZONE
chpasswd:
  expire: false
users:
  - name: $CLOUD_INIT_USERNAME
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - $CLOUD_INIT_PUBLIC_KEY
apt:
  conf: |
    APT {
        Get {
            Assume-Yes 'true';
            Fix-Broken 'true';
        }
    }
    Acquire {
      Check-Date "false";
      Check-Valid-Until "false";
      Max-FutureTime "86400";
    }
package_update: true
package_upgrade: true
package_reboot_if_required: false
packages:
  - bash-completion
  - btop
  - chromium-browser
  - curl
  - dnsutils
  - emacs
  - git
  - htop 
  - hwloc
  - iperf3
  - iputils-ping
  - jq
  - libpam-systemd
  - linux-image-extra-virtual
  - make
  - nano
  - net-tools
  - openssh-server
  - python3
  - python3-pip
  - qemu-guest-agent
  - rig
  - rsync
  - silversearcher-ag
  - ssh-import-id
  - strace
  - sudo
  - sysstat
  - tree
  - unattended-upgrades
runcmd:
  - systemctl start qemu-guest-agent
  - snap remove $(snap list | grep -v snapd | awk '!/^Name|^core/ {print $1}')
  - snap remove snapd
  - apt-get purge snapd -y
  - apt-get autoremove -y
  - apt-get autoclean -y
  - apt-get update -y
  - apt-get upgrade -y
  - systemctl enable unattended-upgrades.service
  - systemctl start unattended-upgrades.service
  - systemctl daemon-reload
  - sed -i 's|#DNSStubListener=yes|DNSStubListener=no|' /etc/systemd/resolved.conf 
  - rm /etc/resolv.conf
  - ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
  - echo -n > /etc/machine-id 
  - rm /var/lib/dbus/machine-id
  - ln -s /etc/machine-id  /var/lib/dbus/machine-id
  - fstrim -av
  - cd /home/$CLOUD_INIT_USERNAME/
  - git clone https://github.com/jamiesmith/UnixEnv.git
  - rm -f .profile .bashrc
  - cd UnixEnv
  - ./link-env.sh /home/$CLOUD_INIT_USERNAME/
  - cd /home/$CLOUD_INIT_USERNAME/
  - mkdir bin
  - cd bin
  - git clone https://github.com/jamiesmith/findgrep.git
  - chown -R $CLOUD_INIT_USERNAME:$CLOUD_INIT_USERNAME /home/$CLOUD_INIT_USERNAME/
  - touch /home/$CLOUD_INIT_USERNAME/.sudo_as_admin_successful

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp-identifier: mac
